### DISCUSSION TITLE
How to enable debug logs in Zilla docker

### DISCUSSION THREAD

**Discussion by lakal-malimage** [aklivity/zilla#1022] [Q&A] [answered]
I would like to enable debug logs in zilla docker container. However, I couldn't find a way to enable it in the documentation. Appreciate it if somebody can help me to enable stdout logging.

**Comment by vordimous** [comment, marked as answer]
Hi @lakal-malimage! Sorry for the late reply. 

You just need to add the `stdout` exporter at the end of your `zilla.yaml` like this:
```
telemetry:
  exporters:
    stdout_logs_exporter:
      type: stdout
```

Here is an [example](https://github.com/aklivity/zilla-examples/blob/main/http.proxy/zilla.yaml#L74C1-L77C19).
