### DISCUSSION TITLE
MQTT clients aren't behaving as expected using the Confluent Cloud IoT Ingest and Control solution for Zilla

### DISCUSSION THREAD

**Discussion by vordimous** [aklivity/zilla#1187] [Q&A] [answered]
We removed TLS on the MQTT side to make it simpler.
Now we are able to connect with MQTT Explorer to the instance and publish a message. We see that data is written to the Kafka topics session, messages and retain.

But it is not working correctly
- Only very few messages are actually written to the Kafka Topics
- Subscribing & Receiving of the telegrams does not work at all.
- Sometimes the MQTT client disconnects and is not able to reconnect for a long time.

[Confluent Cloud IoT Ingest and Control solution docs](https://docs.aklivity.io/zilla/latest/solutions/how-tos/confluent-cloud/iot-ingest-control.html)

`logs`:
```
public.mqtt_server [08/Aug/2024:12:10:52 +0000] BINDING_MQTT_CLIENT_CONNECTED Session authorization (-) was successful for client id (mqtt-explorer-a325789).
```

`zilla.yaml`:
```yaml

name: public
telemetry:
  metrics:
    - stream.opens.sent
    - stream.closes.sent
    - stream.errors.sent
    - stream.errors.received
    - stream.closes.received
    - stream.opens.received
  exporters:
    stdout:
      type: stdout
bindings:
  tcp_server:
    type: tcp
    kind: server
    telemetry:
      metrics:
        - stream.*
    options:
      host: 0.0.0.0
      port: 1883
    exit: mqtt_server
  mqtt_server:
    type: mqtt
    kind: server
    telemetry:
      metrics:
        - stream.*
    options:
      versions:
        - v5
        - v3.1.1
    exit: mqtt_kafka_mapping
  mqtt_kafka_mapping:
    type: mqtt-kafka
    kind: proxy
    telemetry:
      metrics:
        - stream.*
    options:
      topics:
        sessions: iot-zilla-mqtt-sessions
        messages: iot-zilla-mqtt-messages
        retained: iot-zilla-mqtt-retained
      clients:
        - spBv1.0/PAULv0/+/{identity}/#
    exit: kafka_cache_client
  kafka_cache_client:
    type: kafka
    kind: cache_client
    telemetry:
      metrics:
        - stream.*
    exit: kafka_cache_server
  kafka_cache_server:
    type: kafka
    kind: cache_server
    telemetry:
      metrics:
        - stream.*
    options:
      bootstrap:
        - iot-zilla-mqtt-messages
        - iot-zilla-mqtt-retained
    exit: kafka_client
  kafka_client:
    type: kafka
    kind: client
    options:
      servers:
        - ${{aws.secrets.arn:aws:secretsmanager:*:secret:*#bootstrap_server}}
      sasl:
        mechanism: plain
        username: "${{aws.secrets.arn:aws:secretsmanager:*:secret:*#api_key}}"
        password: "${{aws.secrets.arn:aws:secretsmanager:*:secret:*#api_secret}}"
    telemetry:
      metrics:
        - stream.*
    exit: tls_client
  tls_client:
    type: tls
    kind: client
    vault: secure
    telemetry:
      metrics:
        - stream.*
    exit: tcp_client
  tcp_client:
    type: tcp
    kind: client
    telemetry:
      metrics:
        - stream.*
```
