### DISCUSSION TITLE
I have timeout trying to connect my Zilla deployment to Open Telemetry

### DISCUSSION THREAD

**Discussion by vordimous** [aklivity/zilla#1199] [Q&A]
DNS and networking have been confirmed to be correct, but Zilla still can't send any data and logs this error. 

Zilla log:

```
Warning: The otlp exporter could not successfully push data to the specified endpoint for 300 seconds.
```

zilla.yaml telemetry config:

```
    telemetry:
      metrics:
        - http.active.requests
        - http.request.size
        - http.response.size
        - http.duration
        - stream.active.received
        - stream.active.sent
        - stream.opens.received
        - stream.opens.sent
        - stream.data.received
        - stream.data.sent
        - stream.errors.received
        - stream.errors.sent
        - stream.closes.received
        - stream.closes.sent
      exporters:
        stdout_logs_exporter:
          type: stdout
        otlp:
          type: otlp
          options:
            signals:
              - logs
              - metrics
            endpoint:
              protocol: http
              location: http://otel-collector-traces-collector.addons.svc.cluster.local:4318
```
