### DISCUSSION TITLE
Unable to escape ${params.id} from the zilla config for GET/PUT

### DISCUSSION THREAD

**Discussion by vamsi260** [aklivity/zilla#1279] [Q&A] [answered]
Hi Team,
I'm deploying zilla using terraform by templating the zilla.yaml. My Terraform plan is failing with an exception: `Unknown variable params`. I tried few ways to escape the string("${params.id}", and "\${params.id}"), but none worked out. Can some one help? Thanks in advance!

Here is how i'm using it: I have a .tf file where the zilla file is being called.  
`container_definitions = <<DEFINITION
  [
      ${data.template_file.zilla.rendered}
  ]
  DEFINITION
}`

```
data "template_file" "zilla_yaml" {
  template = file("${path.module}/templates/zilla.yml.tmpl")
}

data "template_file" "zilla" {
  template = file("${path.module}/templates/zilla.json")
  vars={
     zilla_yaml     = base64encode(data.template_file.zilla_yaml.rendered)
}
}

```
And the zilla.yml.tmpl has the CRUD config.
 ```
     - when:
          - method: GET
            path: /items/{id}
        exit: north_kafka_cache_client
        with:
          capability: fetch
          topic: events
          filters:
            - key: ${params.id}
```
