### ISSUE TITLE
Attribute support across telemetry exporters. 

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#1049]
**Describe the desired outcome from the user's perspective**
As a DevOps engineer, I expect to specify common and custom attributes for my exported logs and metrics. I want the option to configure the value of any system generated attributes

**Acceptance criteria**
 - Attributes defined in a global scope are exported wherever allowed
 - Exporter specific attributes can be defined
 - Zilla generated attributes have the `zilla.` prefix
 - Zilla generated attributes are also available as `${attribute_name}` parameters that can be used in any custom attributes

example schema:

```
telemetry:
  attributes:
    service.name: ${{ env.OTEL_SERVICE_NAME }}
    service.namespace: ${namespace}
    service.version: ${{ env.ZILLA_VERSION }}
    service.kind: proxy
    another.attribute: my data

  exporters:
    prometheus_metric_exporter:
      type: prometheus
      options:
        attributes:
          prom.binding: prom_ex_${qname}
        endpoints:
          - scheme: http
            path: /metrics
            port: 7190
    otel_exporter_otlp:
      type: otlp
      options:
        attributes:
          otlp.binding: otlp_ex_${qname}
        interval: 5
        signals:
          - logs
        endpoint:
          protocol: http
          location: ${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
```
