### ISSUE TITLE
Support parsing query parameters into the `${params}` object

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#1080]
**Describe the desired outcome from the user's perspective**
As an API admin I need to add more dynamic parameters to a URL query by passing in different query parameters.

**Acceptance criteria**
 - Parse supported URL query parameters into the `${params}` object
 - Create mechanisms to determine when a parameter is empty or missing
 - Handle arrays and allow mapping them to lists in the `zilla.yaml`

**Additional context**
`/topic?keys=key1,keys=key2,keys=key3` would result in a filter:

```yaml
      with:
        capability: fetch
        topic: items-snapshots
        filters:
          - key: key1
          - key: key2
          - key: key3
```

**Comment by jfallows** [comment]
Perhaps we need to keep the config simple and detect that a specific query parameter is multi-valued.

`/topic?keys=key1,keys=key2,keys=key3` would result in a filter:

```yaml
      with:
        capability: fetch
        topic: items-snapshots
        filters:
          - key: ${params.keys}
```

... which implicitly expands to the effective filter below:

```yaml
      with:
        capability: fetch
        topic: items-snapshots
        filters:
          - key: key1
          - key: key2
          - key: key3
```

Internally I think we'd potentially be able to handle this generally as:

```yaml
      with:
        capability: fetch
        topic: items-snapshots
        filters:
          - key: key1 OR key2 OR key3
```

In the case of `key` this is relatively clear, however when the query parameters map to header filters, then it is less clear if the values should always be ORed or sometimes be ANDed since the same header name can repeat in the same message with different values.
