### ISSUE TITLE
Asyncapi doesn't generate schema for catalog with avro format

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#1104]
We are getting empty schema

```
catalogs:
  catalog0:
    type: inline
    options:
      subjects:
        StreampayUser:
          schema: |
            {}
          version: latest
        StreampayCommand:
          schema: |
            {}
          version: latest
        StreampayBalance:
          schema: |
            {}
          version: latest
        StreampayReplies:
          schema: |
            {}
          version: latest
```
