### ISSUE TITLE
AsyncAPI sse kafka filtering support

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#1137]
Add support for sse-kafka filtering.

For example.

```
      - when:
          - path: /payment-requests
        exit: kafka_cache_client1808eec1-480a-4f24-af7d-3a99101cc5b3
        with:
          event:
            id: '["${base64(key)}","${etag}"]'
          topic: payment-requests
          filters:
            - headers:
                zilla:identity: ${guarded['jwt3dc23de6-5185-46f8-86f7-717c3b023d8a'].identity}
```

**Comment by jfallows** [comment]
@akrambek Perhaps we need to indicate this intent via the AsyncAPI spec, then honor it during config generation?

**Comment by jfallows** [comment]
For example, in AsyncAPI operation bindings.
```
bindings:
  x-zilla-sse-kafka:
    filters:
      identity:
        header: zilla:identity
```
