### ISSUE TITLE
Not able to serve streampay demo UI

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#1167]
Not able to serve streampay demo UI

**Steps to reproduce**

1.  Build UI by following README in https://github.com/aklivity/zilla-demos/tree/main/extras-containers/streampay/ui
2. Use below config to server the UI

```
---
name: zilla-streampay-demo-ui
vaults:
  filesystem0:
    type: filesystem
    options:
      keys:
        store: ./tls/localhost-streampay.p12
        type: pkcs12
        password: generated
bindings:
  tcp_server0:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 9090
    exit: http_server0
  http_server0:
    type: http
    kind: server
    exit: http_filesystem_proxy0
  http_filesystem_proxy0:
    type: http-filesystem
    kind: proxy
    routes:
      - when:
          - path: /
        exit: filesystem_server0
        with:
          path: index.html
      - when:
          - path: /{path}
        exit: filesystem_server0
        with:
          path: ${params.path}
  filesystem_server0:
    type: filesystem
    kind: server
    options:
      location: /Users/akramyakubov/workspace/aklivity/zilla-demos/extras-containers/streampay/ui/dist/spa/
```

**Observed behavior
<img width="2558" alt="Screenshot 2024-07-24 at 08 36 11" src="https://github.com/user-attachments/assets/01fe0a87-bdba-4346-a077-570fa231fc2e">
**

As you can see ccs is not being applied and the response for the CSS is empty.
