### ISSUE TITLE
Support Kafka message transformation

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1174]
**Describe the desired outcome from the user's perspective**
As an application developer, I need to transform messages received from a Kafka topic to present via `mqtt-kafka`, `http-kafka` or `sse-kafka` mappings.

**Acceptance criteria**
 - `transforms` should not be required
 - `transforms` should be aligned with Kafka Connect SMTs
 - `transforms` should be evaluated in configured order

**Additional context**
Suggested configuration for transforms.
```
  kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
        topics:
          - name: my-transformed-topic
            transforms:
              - extract-key: ${message.key.id}
              - extract-headers:
                'zilla:identity': ${message.value.user_id}
...
```
See also [Kafka Connect tranformations](https://kafka.apache.org/documentation/#connect_included_transformation).

**Tasks**
 - [ ] `extract-headers`
 - [ ] `extract-key`
 - [ ] ...
