### ISSUE TITLE
Support `extract-headers` kafka message transform

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1175]
Suggested syntax.
```
  kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
        topics:
          - name: my-transformed-topic
            transforms:
              - extract-headers:
                'zilla:identity': ${message.value.user_id}
...
```
