### ISSUE TITLE
Support `extract-key` kafka message transform

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1176]
Suggested syntax.
```
  kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
        topics:
          - name: my-transformed-topic
            transforms:
              - extract-key: ${message.key.id}
...
```
