### ISSUE TITLE
remove the `string` option from Model definitions in the schema and enforce the `object` with `model` property.

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#1238]
**Describe the solution you'd like**
When referencing a model, the current options allow for a shortcut definition of a primitive model.

```
            - status:
                - 401
                - 404
              content-type: 
                - text/plain
              content: string
```

This shortcut is a net neutral or slightly worse given the added complexity of explaining the cases this is allowed and the overall readability of the config.

Using the object definition for all cases adds very little extra code for a more consistent DX:

```
            - status:
                - 401
                - 404
              content-type: 
                - text/plain
              content:
                model: string
```
