### ISSUE TITLE
SSE notifications stop after about 5-6 times when using kafka-sse

### ISSUE THREAD

**Issue by marcinkorda** [aklivity/zilla#1291]
**Describe the bug**

SSE notifications stop after about 5-6 times if a live stream reading is configured.

**To Reproduce**
1. Copy example configuration from https://docs.aklivity.io/zilla/latest/tutorials/sse/sse-intro.html
2. In zilla.yaml replace

```
  south_kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
      bootstrap:
        - events
    exit: south_kafka_client
```

with

```
  south_kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
      bootstrap:
        - events
      topics:
        - name: events
          defaultOffset: live
    exit: south_kafka_client
```

3. Run docker compose and follow instructions from https://docs.aklivity.io/zilla/latest/tutorials/sse/sse-intro.html
4. After 5-6 times you will notice that there is no update on web page despite the fact that kafka is producing new messages.

**Expected behavior**
New messages are seen on web page.

**Zilla Environment:**
Describe the Host environment including:
- Zilla start command: docker compose up -d
- Environment variables: none

Describe a docker container:

```
{
  "Hostname": "50341202a83b",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
  "AttachStdout": true,
  "AttachStderr": true,
  "ExposedPorts": {
    "7114/tcp": {}
  },
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [
    "KAFKA_BOOTSTRAP_SERVER=kafka:29092",
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "ZILLA_VERSION=0.9.97"
  ],
  "Cmd": [
    "start",
    "-v",
    "-e"
  ],
  "Image": "ghcr.io/aklivity/zilla:latest",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": [
    "/opt/zilla/zilla"
  ],
  "OnBuild": null,
  "Labels": {
    "com.docker.compose.config-hash": "1646fa3138ec69db02584c69f25782b3a02f77a72f4084a88b7efa504b523acd",
    "com.docker.compose.container-number": "1",
    "com.docker.compose.depends_on": "kafka:service_started:false",
    "com.docker.compose.image": "sha256:5ae7059361b22ea7447525d814e1982a883c690e98635bf57726cec08ea94041",
    "com.docker.compose.oneoff": "False",
    "com.docker.compose.project": "zilla",
    "com.docker.compose.project.config_files": "/root/wsl_repos/zilla/docker-compose.yaml",
    "com.docker.compose.project.working_dir": "/root/wsl_repos/zilla",
    "com.docker.compose.service": "zilla",
    "com.docker.compose.version": "2.26.1",
    "org.opencontainers.image.ref.name": "ubuntu",
    "org.opencontainers.image.version": "22.04"
  }
}
```
**Attach the `zilla.yaml` config file:**
[zilla_yaml.txt](https://github.com/user-attachments/files/17306837/zilla_yaml.txt)

**Attach the `zilla dump` pcap file:**
[zilla_pcap.zip](https://github.com/user-attachments/files/17306825/zilla_pcap.zip)
