### ISSUE TITLE
Zilla is unresponsive sometimes & the app logs Stopped but accepts the CRUD requests

### ISSUE THREAD

**Issue by vamsi260** [aklivity/zilla#1312]
Hi Team,
I'm running zilla with kafka crud use case, where i primarily focused on POST. Initially the app was running fine with 0.9.89 , able to get 204 response when we hit it with curl. We see an abnormal behaviour when using curl on CRUD operations. the curl is stuck and awaiting for the response back from the server. I see a log entry but actually the request is not hitting the zilla app.
October 24, 2024 at 22:00 (UTC+5:30)

```
Zilla:north_http_server [24/Oct/2024:16:30:47 +0000] BINDING_HTTP_REQUEST_ACCEPTED - POST [http://zilla-test.exp-aws.net:80/items](http://zilla-test.exp-aws.net/items)
```

Strange observation is, if the existing curl is forced to stop and re-run the curl POST couple of times, it works and gives 204 response, but soon after it'll be back in the stuck mode. I don't see much in the logging on what's really happening. I tried deploying a new image version 0.9.98  just to isolate the issue. But it's the same behaviour. I want to know where exactly the problem lies in. please help me on how can i enable better logging. The additional change to the existing zilla config is added telemetry at each section. I don't think that's a problem!

Observations: when we try CRUD operations, 
1. Sometimes `stuck `in getting the response forever.
2. Sometimes we get the `204` response 
3. Sometimes we see `Empty reply from server.`
4. We see Zilla logging `Stopped` abruptly, but still accepts the request.

Here is some additional info. this is something which popped in the log when a load run was triggered from jmeter( 8MPBS network 800 TPS load with 10kb of payload size)
```
2024-10-29T16:59:36.649+05:30.       java.lang.IllegalArgumentException: invalid offset: -65536
2024-10-29T16:59:36.649+05:30.        stopped
```

Attached a Diagnostic zip [zilla_20241028121032.tar.gz](https://github.com/user-attachments/files/17543930/zilla_20241028121032.tar.gz)

Env: Zilla is deployed on AWS ECS fargate. The Kafka implementation is Confluent Cloud.

zilla.yaml config:
```yaml
---
name: Zilla
bindings:
  north_tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port:
        - 7114
    routes:
      - when:
          - port: 7114
        exit: north_http_server
    telemetry:
      metrics:
        - stream.*
  north_http_server:
    type: http
    kind: server
    routes:
      - when:
          - headers:
              :scheme: http
        exit: north_http_kafka_mapping
    telemetry:
      metrics:
        - http.*
  north_http_kafka_mapping:
    type: http-kafka
    kind: proxy
    routes:
      - when:
          - method: POST
            path: /items
        exit: north_kafka_cache_client
        with:
          capability: produce
          topic: events
          key: $${idempotencyKey}
      - when:
          - method: DELETE
            path: /items/{id}
        exit: north_kafka_cache_client
        with:
          capability: produce
          topic: events
          key: $${params.id}
    telemetry:
      metrics:
        - stream.*
        - http.*
  north_kafka_cache_client:
    type: kafka
    kind: cache_client
    exit: south_kafka_cache_server
  south_kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
      bootstrap:
        - events
    exit: south_kafka_client
  south_kafka_client:
    type: kafka
    kind: client
    options:
      servers:
        - ${kafka_bootstrap_host}:9092
      sasl:
        mechanism: plain
        username: ${kafka_username}
        password: ${kafka_password}
    exit: south_tls_client
  south_tls_client:
    type: tls
    kind: client
    exit: south_tcp_client
  south_tcp_client:
    type: tcp
    kind: client
telemetry:
  metrics:
    - http.active.requests
    - http.duration
    - http.request.size
    - http.response.size
    - stream.active.received
    - stream.active.sent
    - stream.opens.received
    - stream.opens.sent
    - stream.data.received
    - stream.data.sent
    - stream.errors.received
    - stream.errors.sent
    - stream.closes.received
    - stream.closes.sent
  exporters:
    stdout_logs_exporter:
      type: stdout
    prometheus_metric_exporter:
      type: prometheus
      options:
        endpoints:
          - scheme: http
            path: /metrics
            port: 7190
```
Attached.
[zilla.yaml.zip](https://github.com/user-attachments/files/17544812/zilla.yaml.zip)

Slack ref: https://aklivitycommunity.slack.com/archives/C027SEH2KRC/p1730119696631149?thread_ts=1729788282.245839&cid=C027SEH2KRC

Let me know if you need anything more!
