### ISSUE TITLE
Connection to MQTT server over WebSocket fails from web browser

### ISSUE THREAD

**Issue by epieffe** [aklivity/zilla#1374]
**Describe the bug**
Connection to Zilla MQTT server over WebSocket fails **from web browser**.

 The same javascript code executed on nodejs, outside a web browser, connects successfully.

**To Reproduce**
To quickly reproduce the issue I created a GitHub repo with a `compose.yaml` file that starts Zilla with Kafka and a simple `index.html` page that uses [MQTT.js](https://github.com/mqttjs/MQTT.js) to connect to the MQTT server. All the steps to reproduce the problem are described in the README:

https://github.com/epieffe/zilla-mqtt-ws-test

In short:
1. Start Zilla with MQTT and WebSocket bindings
2. Connect to the MQTT server from a web browser
3. The connection fails

**Expected behavior**
The web browser successfully connects to Zilla MQTT server.

**Additional context**
I ran the same `index.html` with the EMQX MQTT broker and it successfully connects, both on Firefox and Google Chrome.

**Comment by ankitk-me** [comment]
We have identified the issue with the config, please update `http_server` with mentioned change:

```
options:
      access-control:
        policy: cross-origin
```

After the update, `http_server` should look like:

```
http_server:
    type: http
    kind: server
    options:
      access-control:
        policy: cross-origin
    routes:
      - when:
          - headers:
              :scheme: http
              upgrade: websocket
          - headers:
              :scheme: https
              upgrade: websocket
        exit: ws_server
```

Screenshot for validation:

![Image](https://github.com/user-attachments/assets/f324b46d-c515-4e1e-b471-cac70d9c3119)
