### ISSUE TITLE
Support JWT Claims for Dynamic Kafka Topic Routing

### ISSUE THREAD

**Issue by hoegertn** [aklivity/zilla#1511]
## Summary

Enable dynamic Kafka topic routing based on JWT token claims (e.g., subject, user ID, or custom claims) to implement user-isolated topic access patterns.

## Current Behavior

Currently, Zilla only supports path parameters for topic selection in the `http-kafka` proxy binding. Topic names must be explicitly defined in the URL path pattern:

```yaml
routes:
  - when:
      - method: GET
        path: /topics/{topic}
    exit: kafka_cache_client
    with:
      topic: ${params.topic}
```

## Desired Behavior

Allow topic names to be derived from JWT claims, enabling user-specific topic isolation without exposing the topic name in the URL:

```yaml
routes:
  - when:
      - method: GET
        path: /my-data
    exit: kafka_cache_client
    with:
      topic: user-${identity.subject}  # or ${identity.claims.userId}
```

## Use Case

In multi-tenant SaaS applications or banking/financial services, we need to ensure strict data isolation where each user can only access their own Kafka topic. This pattern is common for:

- Personal data streams
- Account-specific event logs
- User-isolated message queues
- Compliance with data privacy regulations

### Example Scenario

A banking application where each customer's transactions are stored in individual Kafka topics:

1. User authenticates and receives JWT with `sub: "customer-12345"`
2. User makes request to `GET /transactions`
3. Zilla routes to Kafka topic `transactions-customer-12345` based on JWT subject
4. User can only ever access their own topic, enforcing data isolation at the infrastructure level

## Proposed Implementation

Extend the `with` configuration in http-kafka bindings to support identity claims:

```yaml
bindings:
  http_server:
    type: http
    kind: server
    options:
      authorization:
        jwt:
          issuer: https://auth.example.com
          audience: https://api.example.com
    routes:
      - when:
          - method: GET
            path: /my-stream
        exit: kafka_proxy
        with:
          topic: ${identity.subject}-stream  # New: Reference JWT claims

  kafka_proxy:
    type: http-kafka
    kind: proxy
    routes:
      - when:
          - method: GET
        exit: kafka_cache_client
        with:
          capability: fetch
          topic: ${topic}  # Receives interpolated value from upstream
```

## Technical Considerations

1. **Claim Access**: Support common JWT claim paths:
   - `${identity.subject}` - Standard JWT subject
   - `${identity.claims.customField}` - Custom claims
   - `${identity.preferred_username}` - OIDC standard claims

2. **Topic Name Validation**: Ensure resulting topic names are valid Kafka identifiers

3. **Performance**: Claim extraction should have minimal overhead since JWT is already parsed for authorization

## Alternative Workarounds

Currently, achieving this requires:
- Exposing user IDs in URLs (security concern)
- Implementing a custom proxy service in front of Zilla
- Using separate Zilla configurations per user (not scalable)

## References

- Current documentation: https://docs.aklivity.io/zilla/latest/reference/config/bindings/http-kafka/proxy.html#with-topic
- Related binding configuration: https://docs.aklivity.io/zilla/latest/reference/config/bindings/binding-http.html#authorization

**Comment by jfallows** [comment]
We should also support the same capability in `sse-kafka`.

```
guards:
  authn_jwt:
    type: jwt
    options:
      issuer: https://auth.example.com
      audience: https://api.example.com
...    

bindings:
...
  http_server:
    type: http
    kind: server
    options:
      authorization:
        authn_jwt:
          credentials:
            headers:
              authorization: Bearer {credentials}
    exit: sse_server

  sse_server:
    type: sse
    kind: server
    exit: http_kafka_proxy

  sse_kafka_proxy:
    type: sse-kafka
    kind: proxy
    routes:
      - when:
          - path: /my-stream
        exit: kafka_cache_client
        with:
          capability: fetch
          topic: ${guarded['authn_jwt'].identity}-stream
```
