### ISSUE TITLE
When starting up in verbose mode make sure there is a newline after printing the config

### ISSUE THREAD

**Issue by attilakreiner** [aklivity/zilla#157]
**Is your feature request related to a problem? Please describe.**
When starting up in verbose mode the output looks weird if there isn't a newline at the end of the config.

**Describe the solution you'd like**
When starting up in verbose mode if there is no newline at the end of the config the `started` message is appended to the last line of the config which looks weird. Pls note the line `kind: serverstarted`:
```
---
name: example
bindings:
  tcp_server0:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 12345
    exit: echo_server0
  echo_server0:
    type: echo
    kind: serverstarted
stopped 
```
My suggestion is that we should add a newline when printing the config if it's not present, e.g.
```
---
name: example
bindings:
  tcp_server0:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 12345
    exit: echo_server0
  echo_server0:
    type: echo
    kind: server
started
stopped 
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
