### ISSUE TITLE
Support gRPC Kafka mapping

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#184]
```
---
name: test
bindings:
  grpc_kafka_proxy0:
    type: grpc-kafka
    kind: proxy
    exit: kafka_cache_client0
  kafka_cache_client0:
    type: kafka
    kind: cache_client
    exit: kafka_cache_server0
  kafka_cache_server0:
    type: kafka
    kind: cache_server
    exit: kafka_client0
  kafka_client0:
    type: kafka
    kind: client
    exit: tcp0
```
