### ISSUE TITLE
Support Kafka gRPC mapping

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#185]
```
---
name: test
bindings:
  grpc_client0:
    type: grpc
    kind: client
    exit: http_client0
  kafka_grpc_proxy0:
    type: grpc-kafka
    kind: proxy
    exit: kafka_cache_client0
  kafka_cache_client0:
    type: kafka
    kind: cache_client
    exit: kafka_cache_server0
  kafka_cache_server0:
    type: kafka
    kind: cache_server
    exit: kafka_client0
  kafka_client0:
    type: kafka
    kind: client
    exit: tcp0
```
