### ISSUE TITLE
Integrate Prometheus by exporting local metrics over HTTP

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#193]
Note: requires design https://github.com/aklivity/zilla/issues/109 and https://github.com/aklivity/zilla/issues/111.

Support the `prometheus` kind of telemetry `exporter`, contributed via the `telemetry-prometheus` component.

```
    exporters:
      prometheus0:
        kind: prometheus
        options:
          endpoint: http://localhost:10080
```
