### ISSUE TITLE
Initiating kafka merge stream  without filter doesn't fetch messages

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#207]
**Describe the bug**
Initiating kafka merge stream without a filter doesn't fetch any messages. For example.

```
   remote_server0:
    type: kafka_grpc
    kind: remote_server
    options:
      scheme: http
      authority: localhost:9090
      entry: grpc_client0
      acks: leader_only
    routes:
    - exit: kafka_cache_client0
      when:
      - topic: requests
        reply-to: responses
```

**Expected behavior**
Should send messages on reply stream.
