### ISSUE TITLE
Enhance `grpc` related binding configuration

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#226]
Recommend enhancing `grpc`, `grpc-kafka` and `kafka-grpc` binding configuration to increase consistency and improve readability.

`grpc`
```
grpc_server0:
  type: grpc
  kind: server
  options:
    services:
      - proto/echo.proto
  routes:
    - when:
        - method: example.EchoService/*
          metadata:
            custom-text: custom value
            custom-binary:
              base64: Y3VzdG9tIHZhbHVl
      exit: echo_server0
``` 

`grpc-kafka`
```
grpc_kafka_proxy0:
  type: grpc-kafka
  kind: proxy
  options:
    reliability:
      field: 32767
      metadata: last-message-id
    idempotency:
      metadata: idempotency-key
    correlation:
      headers:
        service: zilla:service
        method: zilla:method
        correlation-id: zilla:correlation-id
        reply-to: zilla:reply-to
  routes:
    - when:
        - method: example.FanoutService/*
          metadata:
            custom-text: custom value
            custom-binary:
              base64: Y3VzdG9tIHZhbHVl
      exit: kafka_cache_client0
      with:
        capability: fetch
        topic: messages
        filters:
          key: custom-key
          headers:
            custom-text: custom-value
    - when:
          method: example.EchoService/*
          metadata:
            custom-text: custom value
            custom-binary:
              base64: Y3VzdG9tIHZhbHVl
      exit: kafka_cache_client0
      with:
        capability: produce
        topic: requests
        acks: leader_only
        key: custom-key
        overrides:
          custom-text: custom-value
        reply-to: responses
```

`kafka-grpc`
```
kafka_grpc_proxy0:
  type: kafka-grpc
  kind: remote_server
  entry: kafka_cache_client0
  options:
    acks: leader_only
    idempotency:
      metadata: idempotency-key
    correlation:
      headers:
        service: zilla:service
        method: zilla:method
        correlation-id: zilla:correlation-id
        reply-to: zilla:reply-to
  routes:
    - exit: grpc0
      when:
        - topic: requests
          reply-to: responses
          method: example.EchoService/*
      with:
        scheme: http
        authority: localhost:8080
```
