### ISSUE TITLE
Check for files on startup when the zilla.yaml specifies paths to files or directories

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#292]
**Is your feature request related to a problem? Please describe.**
If a .proto file is not accessible by Zilla there isn't a clear indication. The current error message is cryptic:

```
Jun 29, 2023 1:28:14 PM org.eclipse.yasson.internal.Unmarshaller deserializeItem
SEVERE: Problem adapting object of type class io.aklivity.zilla.runtime.engine.config.NamespaceConfig to interface jakarta.json.JsonObject in class class io.aklivity.zilla.runtime.engine.internal.config.NamespaceAdapter
Configuration parsing error: Problem adapting object of type class io.aklivity.zilla.runtime.engine.config.NamespaceConfig to interface jakarta.json.JsonObject in class class io.aklivity.zilla.runtime.engine.internal.config.NamespaceAdapter
```

**Describe the solution you'd like**
For elements that map to the file system, it would be nice for zilla to warn or error when it doesn't find the file or folder it is looking for. 

**Describe alternatives you've considered**
The filesystem server and proxy also let you specify files that doesn't exist but don't give you any indication other than an eventual 404, which can be a number of different problems.

**Additional context**
`grpc` (protobuf), `openapi`+`asyncapi`+`openapi-asyncapi`, `tls` (filesystem vault)

**Comment by jfallows** [comment]
When addressing this we need to take into consideration that the `.proto` resource(s) could be delivered remotely via `http` not necessarily local via filesystem.

**Comment by vordimous** [comment]
Adding some of the filesystem situations I tested.

```yaml
  http_filesystem_proxy:
    type: http-filesystem
    kind: proxy
    routes:
      - when:
          - path: /
        with:
          path: index.html # if this is excluded, zilla doesn't throw an error
        exit: filesystem_server
  filesystem_server:
    type: filesystem
    kind: server
    options:
      location: /var/www/ # if this is a specific file instead of a dir, zilla doesn't throw and error
```
