### ISSUE TITLE
Support dynamic message key and headers in `grpc-kafka`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#380]
Support dynamic message key and headers in `grpc-kafka`  when
 - producing to Kafka, based on `message` record
 - fetching from Kafka, based on request `metadata`

For example:
```
bindings:
  grpc_kafka0:
    type: grpc
    kind: server
    options:
      services:
        ...
    routes:
      - when:
          - method: example.ChatService/send
        exit: kafka_cache_client0
        with:
          capability: produce
          topic: chat-messages
          key: ${message.chatroom}
      - when:
          - method: example.ChatService/receive
        exit: kafka_cache_client0
        with:
          capability: fetch
          topic: chat-messages
          filters:
            - key: ${metadata.chatroom}
```

Note: `grpc` metadata is already sent between `grpc` binding and `grpc-kafka` binding at the beginning of the stream, however only `grpc` binding currently understands the structure of the payload, so we need to determine how to make `grpc-kafka` payload type aware, such that expressions like `${message.chatroom}` can understand which field number needs to be extracted from the payload and inserted into the Kafka message key for example.
