### ISSUE TITLE
Bootstrap options on cache_client vs cache_server for the kafka binding

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#388]
**Describe the bug**

Shown below, the zilla schema does not care that the bootstrap options were used for both kinds of kafka bindings. This doesn't result in an error but a user can easily mistake these configs and assume the wrong behavior is being applied.

```
  kafka_cache_client:
    type: kafka
    kind: cache_client
    options:
      bootstrap:
        - items-crud
    exit: kafka_cache_server
  kafka_cache_server:
    type: kafka
    kind: cache_server
    options:
      bootstrap:
        - items-crud
    exit: kafka_client
```

**Expected behavior**
Show an error to the user if the bootstrap options are used with the wrong `kind`.
