### ISSUE TITLE
syntax check mqtt topic names and topic filters in zilla.yaml

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#521]
**Is your feature request related to a problem? Please describe.**
When I use an invalid topic name/filter Zilla will crash with a stack trace `Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*'`

```
    - when:
        - publish:
            - topic: "*"
        - subscribe:
            - topic: "*"
```

**Describe the solution you'd like**
Add validation checks when parsing the zilla.yaml
