### ISSUE TITLE
the `tls` binding throws NPE if there are no `options` defined

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#612]
**Describe the bug**
Zilla throws a NullPointerException on startup if a `tls` binding is defined with a proper exit but no options. The workaround was to add a `mutual: none` param:

```yaml
  south_tls_client:
    type: tls
    kind: client
    options:
      mutual: none
    exit: south_tcp_client
```

**To Reproduce**
try to use a tls binding with no options defined:

```yaml
  south_tls_client:
    type: tls
    kind: client
    exit: south_tcp_client
```
