### ISSUE TITLE
Support `asyncapi` `http` proxy using `asyncapi.yaml`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#739]
**Describe the desired outcome from the user's perspective**
As an AsyncAPI consumer, I want to configure zilla as `http` proxy using `asyncapi.yaml` more directly in `zilla.yaml`.

**Acceptance criteria**
 - `asyncapi` `server` binding configured via `asyncapi.yaml` for `http`
 - `asyncapi` `client` binding configured via `asyncapi.yaml` for `http`
 - only `asyncapi` `server` binding and `asyncapi` `client` binding needed to configure `asyncapi` `http` proxy

**Additional context**
Syntax similar to the following in `zilla.yaml` using composite bindings.
```yaml
bindings:
  asyncapi_server:
    type: asyncapi
    kind: server
    options:
      specs:
        - http/asyncapi.yaml
    exit: asyncapi_client0
  asyncapi_client:
    type: asyncapi
    kind: client
    options:
      specs:
        - http/asyncapi.yaml
```
