### ISSUE TITLE
Support `openapi` `http` proxy using `openapi.yaml`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#740]
**Describe the desired outcome from the user's perspective**
As an OpenAPI consumer, I want to configure zilla as `http` proxy using `openapi.yaml` more directly in `zilla.yaml`.

**Acceptance criteria**
 - `openapi` `server` binding configured via `openapi.yaml`
 - `openapi` `client` binding configured via `openapi.yaml`
 - only `openapi` `server` binding and `openapi` `client` binding needed to configure `openapi` proxy

**Additional context**
Syntax similar to the following in `zilla.yaml` using composite bindings.
```yaml
bindings:
  openapi_server:
    type: openapi
    kind: server
    options:
      specs:
        - http/openapi.yaml
    exit: openapi_client0
  openapi_client:
    type: openapi
    kind: client
    options:
      specs:
        - http/openapi.yaml
```
