### ISSUE TITLE
Support `mqtt` to `kafka` proxy using `asyncapi.yaml`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#741]
**Describe the desired outcome from the user's perspective**
As an AsyncAPI consumer, I want to configure zilla as `mqtt` proxy to `kafka` using `asyncapi.yaml` more directly in `zilla.yaml`.

**Acceptance criteria**
 - `asyncapi` `server` binding configured via `mqtt` `asyncapi.yaml`
 - `asyncapi` `client` binding configured via `kafka` `asyncapi.yaml`
 - `asyncapi` `proxy` binding configured via `mqtt` and `kafka` `asyncapi.yaml`
 - only `asyncapi` `server`, `proxy` and `client` bindings needed to configure `mqtt` to `kafka` proxy

**Additional context**
Syntax similar to the following in `zilla.yaml` using composite bindings.
```yaml
bindings:
  asyncapi_server:
    type: asyncapi
    kind: server
    options:
      specs:
        - mqtt/asyncapi.yaml
    exit: asyncapi_proxy
  asyncapi_proxy:
    type: asyncapi
    kind: proxy
    options:
      specs:
        - mqtt/asyncapi.yaml
        - kafka/asyncapi.yaml
    routes:
      - when:
           - operation: ... # mqtt asyncapi operation id
         exit: asyncapi_client
         with:
           operation: ... # kafka asyncapi operation id
  asyncapi_client:
    type: asyncapi
    kind: client
    options:
      specs:
        - kafka/asyncapi.yaml
```
