### ISSUE TITLE
Support `http` to `kafka` proxy using `openapi.yaml` and `asyncapi.yaml`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#742]
**Describe the desired outcome from the user's perspective**
As an OpenAPI and AsyncAPI consumer, I want to configure zilla as `http` proxy to `kafka` using  `openapi.yaml` and `asyncapi.yaml` more directly in `zilla.yaml`.

**Acceptance criteria**
 - `openapi` `server` binding configured via `openapi.yaml`
 - `openapi-asyncapi` `proxy` binding configured via `openapi.yaml` and `asyncapi.yaml`
 - `asyncapi` `client` binding configured via `kafka` `asyncapi.yaml`
 - only `openapi` `server`, `openapi-asyncapi` `proxy`, and `asyncapi` `client` bindings needed to configure `http` to `kafka` proxy

**Additional context**
Syntax similar to the following in `zilla.yaml` using composite bindings.
```yaml
bindings:
  openapi_server:
    type: openapi
    kind: server
    options:
      specs:
        - http/openapi.yaml
    exit: openapi_asyncapi_proxy
  openapi_asyncapi_proxy:
    type: openapi-asyncapi
    kind: proxy
    options:
      specs:
        - http/openapi.yaml
        - kafka/asyncapi.yaml
    routes:
      - when:
          - operation: ... # openapi operation id
        exit: asyncapi_client
        with:
          operation: ... # kafka asyncapi operation id
  asyncapi_client:
    type: asyncapi
    kind: client
    options:
      specs:
        - kafka/asyncapi.yaml
```
