### ISSUE TITLE
Zilla is validating `env` vars before replacing them. 

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#795]
**Describe the bug**
Zilla is validating `env` vars before replacing them. 

```
[23,31][/telemetry/exporters/prometheus_metric_exporter/options/endpoints/0/port] The value must be of integer type, but actual type is string.
error
io.aklivity.zilla.runtime.engine.config.ConfigException: Engine configuration failed
```

**To Reproduce**
```
docker run -v ./zilla.yaml:/etc/zilla/zilla.yaml --env PORT="7190" ghcr.io/aklivity/zilla:0.9.68 start -v
```
zilla.yaml
```
---
name: example
bindings:
  north_tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 12345
    exit: north_echo_server
  north_echo_server:
    type: echo
    kind: server

telemetry:
  exporters:
    prometheus_metric_exporter:
      type: prometheus
      options:
        endpoints:
          - scheme: http
            path: /metrics
            port: ${{env.PORT}}
```
